### PR TITLE
fix for index arithmetic

### PR DESCRIPTION
**Pull request by sudiptoguha**
*Description of changes:* The extrapolation code for the cyclic case had incorrect index arithmetic

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by wnbts** [comment]
Looks good. Is it possible to add tests to verify and prevent regressions?

**Comment by jotok** [comment]
I believe that the existing code can throw an NPE. Given that we are still in alpha, there is no existing test coverage for the extrapolation methods, and writing unit tests for the extrapolate methods will require some finicky mocking, I'm inclined to merge this PR as is and create a new Issue to add test coverage. Does that work for you  @wnbts ?

**Comment by wnbts** [comment]
OK

**Comment by jotok** [comment]
Issue to add test coverage #10

**Pull request merged**
